version: "3.8"

# execute `docker-compose up`
# create and start multiple containers in one command!

services:
  redis-channel1:
    image: redis-double
    ports:
      - "8000:6379"
    working_dir: /data
#    volumes:
#      - redis-data:/var/lib/redis/channel_1

  redis-channel2:
    image: redis-double
    ports:
      - "7100:6379"
    working_dir: /data
#    volumes:
#      - redis-data:/var/lib/redis/channel_2

volumes:
  redis-data:
